// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiDkCQJGBfPWrFm6T0yW8pHvS-Jdk1J2g',
    appId: '1:244284427018:web:28ca618fa5cf21f91188f3',
    messagingSenderId: '244284427018',
    projectId: 'logsys-login',
    authDomain: 'logsys-login.firebaseapp.com',
    storageBucket: 'logsys-login.appspot.com',
    measurementId: 'G-H7GNT3C5K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqDafiys0Ba3ccoKtyw0jFtZLeSV2uXFM',
    appId: '1:244284427018:android:e40cfb8014b6f6d11188f3',
    messagingSenderId: '244284427018',
    projectId: 'logsys-login',
    storageBucket: 'logsys-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9mlSQhjrk_YFkcbBxWZkKVnz3LxbH2r4',
    appId: '1:244284427018:ios:a40d2f37e329929f1188f3',
    messagingSenderId: '244284427018',
    projectId: 'logsys-login',
    storageBucket: 'logsys-login.appspot.com',
    iosBundleId: 'com.example.logsys',
  );
}
